### ISSUE TITLE
TypeError thrown

### ISSUE THREAD

**Issue by petobena** [skaut/skaut-fio-bank-transactions#24]
Ahojte, zadal som shortcode [fio]  a dostanem chybu:

`TypeError thrown`
`Argument 1 passed to FioTransactions\Frontend\Shortcode::processShortcode() must be of the type array, string given, called in /web/htdocs5/xxx/home/www/wp-includes/shortcodes.php on line 343`

poprosim o radu
Dakujem

**Comment by marekdedic** [comment]
Ahoj, nejsem autorem pluginu, ale vypadá to, že shortcode vyžaduje parametr `account` :)

**Comment by petobena** [comment]
@marekdedic ahoj Marek, zial skusam aj s nim, uz nepise chybu, ale nezobrazi ziadne transakcie, tak neviem ako dalej

**Comment by TheValdis** [comment]
Bohužel stejný problém, po zadání [fio account] je stránka prázdná a nic nezobrazuje. Vypadá to, že je plugin nefunkční. Nějaká rada od autorů? (Plugin také zobrazuje pouze název a token, žádné jiné nastavení není, ani daný shortcode)

**Comment by marekdedic** [comment]
No ale ten parametr account očekává nějakou hodnotu, jakože `[fio account="123..."]`. Tipoval bych, že číslo účtu.

Ale možná je to i rozbitý, to nevím :D

**Comment by TheValdis** [comment]
Jako jasně, to chápu :D akorát je škoda, že k tomu, jak by to mělo vypadat atd. nejsou žádné informace nebo aspoň obrázek funkčního zobrazení.

**Comment by kalich5** [comment]
Nová verze je nahraná, přes "klasický editor" si můžete účet zobrazit na webu.
https://cs.wordpress.org/plugins/skaut-fio-bank-transactions/

**Comment by kalich5** [comment]
https://napoveda.skaut.cz/dobryweb/skaut-fio-bank-transactions
