### ISSUE TITLE
Call to undefined method GuzzleHttp\Utils::chooseHandler()

### ISSUE THREAD

**Issue by petobena** [skaut/skaut-fio-bank-transactions#26]
Ahojte,
po novej aktualizacii mi to hadze:

`Error thrown
Call to undefined method GuzzleHttp\Utils::chooseHandler()`

**Comment by davidulus** [comment]
Ahoj @petobena, zkus prosím smazat celou složku pluginu na FTP (wp-content/plugins/skaut-fio-bank-transactions) a potom plugin nainstalovat znovu.

**Comment by kalich5** [comment]
Akorát jsem to chtěl napsat taky, zkoušel jsem to na 3 webech a nikdy to nehodilo jedinou chybu. Všude PHP 7.4 a poslední WordPress.

**Comment by petobena** [comment]
zial, to nepomohlo, stale ta ista chyba

**Comment by davidulus** [comment]
@petobena Velmi pravděpodobně je problém v tom, že nějaký z dalších pluginů, který máš aktivovaný, používá také knihovnu Guzzle, ale v jiné verzi. Tím dochází ke konfliktům / vzájemné nekompatibilitě pluginů.
Mohu Tě požádat o výčet pluginů, které používáš?

**Comment by petobena** [comment]
mam tieto pluginy:

Advanced Shipment Tracking for WooCommerce - 3.2.3
BackWPup - 3.8.0
Breadcrumb NavXT - 6.6.0
Cookie Notice & Compliance for GDPR / CCPA - 2.0.3
Easy Watermark - 1.0.11
Email Log - 2.4.5
FileBird Lite - 4.7.2
Fio bank - transactions - 1.1.1
Flexible Shipping - 4.3.1
Jetpack od WordPress.com - 9.6.1
Loco Translate - 2.5.2
NextGEN Gallery - 3.9.3
Orbit Fox Companion by Neve theme - 2.10.4
Product Configurator for WooCommerce - 1.2.12
Really Simple SSL - 4.0.14
ShopMagic for WooCommerce - 2.23.2
Slovenská pošta - ePodací hárok - 1.0.2
Smash Balloon Instagram Feed - 2.9
Templates Patterns Collection - 1.1.7
To Top - 2.2.1
Under Construction - 3.88
Variation Swatches for WooCommerce - 1.1.14
Widget for Social Page Feeds - 6.1
WooCommerce - 5.2.2
WooCommerce PDF Invoices & Packing Slips - 2.8.3
WooCommerce Product Filter by WooBeWoo - 1.4.8
WooCommerce Stock Manager - 2.5.7
WP Rocket - 3.8.7
WP Statistics - 13.0.8
WPify Woo - 3.0.6
XT WooCommerce Floating Cart - 2.3.2
Yoast SEO - 16.1.1
