### ISSUE TITLE
Chyba při spojení s Fio bankou. Zkuste to znovu.

### ISSUE THREAD

**Issue by TheValdis** [skaut/skaut-fio-bank-transactions#28]
Zdravím,
při zobrazení shortcodu na stránce mi to vyhodí "Chyba při spojení s Fio bankou. Zkuste to znovu." Token by měl být vygenerován pro zobrazování (jedná se o transparentní účet). Žádné další error to nezobrazuje, můžete prosím poradit kde by mohla být chyba?

**Comment by kalich5** [comment]
Tak stačí kliknout na "Zkusit znovu" a načte se tabulka. U toho FIO api je omezení, že se může číst jen každou minutu myslím. A proto skáče takhle hláška...

**Comment by TheValdis** [comment]
Samozřejmě "Zkusit znovu" nefunguje, jinak bych nepsal :) Ono se ta tabulka nezobrazila zatím nikdy, proto se ptám, kde by mohla být chyba, když je Token, PHP i WP ok a nic mi to neblokuje (kontrola v konzoli prohlížeče). Děkuji

**Comment by kalich5** [comment]
Zkusit debug, jestli něco nevypíše. Zkusil bych znova vygenerovat Token. A taky by se hodil odkaz na web.

**Comment by TheValdis** [comment]
Debug vyzkoušen a také nic. Odkaz ->https://www.behpro.cz/test-fio/
