### ISSUE TITLE
[WordPress Plugin Directory] Request: Fio Bank transactions

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-fio-bank-transactions#3]
## We cannot accept your plugin with this name

Your autogenerated plugin slug was this: fio-bank-transactions

Since you don’t appear to legally represent that group, we need to change the plugin slug.

We recommend the following: sakut-fio-bank-transactions

A rather lengthy explanation of why is included below, but the tl;dr is that we're no longer accepting plugins that begin with (or are in total) a trademarked product name or term as the name or slug of a plugin (ex: Facebook or google-maps-bathrooms). Nor are we accepting plugins that include the name of another plugin at the beginning of the name/slug (eg: contact-form-7-music), UNLESS you legally represent that service/plugin/theme/etc.

Please reply to this email with what slug you’d like. We’ll edit it slug for you.

You DO NOT need to edit your code for this. ALL we need is to be on the same page for the plugin slug :)

If you DO work for the company, reply to this email and tell us. We can fix your submission.

Here's the long stuff.

The slug for your plugin is generated based on the name you put in your main plugin file, with hyphens inserted in place of spaces. This means if you were to name your plugin "My Really Cool Cookie Jam" then your URL on WordPress.org would be http://wordpress.org/plugins/my-really-cool-cookie-jam

This becomes a larger issue when plugins use the names of other plugins in their own.

For example, if you have written an add-on plugin for WooCommerce, you may not name it "WooCommerce Improved Product Search" as that would generate the slug "woocommerce-improved-product-search" and that would conflict with the trademark of 'WooCommerce.' That said, it would be acceptable to submit the name "Woo Improved Product Search" which would use the slug "woo-improved-product-search" (woo not being trademarked you see).

As another example, if you have a plugin that integrates a service with a Easy Digital Downloads, you may call it "My Service Integration for Easy Digital Downloads", but you may not use "Easy Digital Downloads - My Service Integration". Alternately you could use 'EDD My Service Integration' and that too would be permitted.

None of this impacts your display name of your plugin. The display name is generated from your readme.txt, and that can be whatever you'd like. Keep in mind, you should use "My Product for Other Product" as the description. Consider the example of Keurig. If you made an eco-friendly brew cup, you could market it "EcoBrew Pod for Keurig" but you could NOT attempt to market it as "Keurig EcoBrew Pod." The latter implies a direct relationship to Keurig and is actually against the law in some countries.

You are more than welcome, and encouraged, to include it in the description of the plugin in the ReadMe.txt file, but it cannot be in the name/slug of the plugin as described above.

If you got all the way down here and forgot what to do next, just press reply to this email and tell us what slug you’d like, or if you need to transfer the plugin to a different account. We can fix the plugin.

**Comment by kalich5** [comment]
@davidulus Zkusil jsem, jestli by to prošlo na WordPress.org. Ale ten název fio-bank-transactions bych nechal, nechápu co se jim na tom nelíbí...

**Comment by kalich5** [comment]
Mě by přišlo dobré, se držet toho nového názvu. Jasně vyjadřuje, že je to FIO banka a její transakce. Nechápu, co se jim na tom nelíbí...

**Comment by kalich5** [comment]
I'm sorry but you just sent us MULTIPLE emails with multiple proposed plugin slugs.

You do not LEGALLY represent FIO Bank. Therefore we cannot let you use fio-bank-transactions

That's just not an option. If you'd read the email carefully, you would have noticed two important things:

1) You DO NOT need to edit your plugin code (we don't need you to email us new code)

2) We USED to allow those sorts of names, but we don't anymore.

So no, you cannot have it.

**Comment by davidulus** [comment]
Tak bych to zkusil přejmenovat na transactions-from-fio-bank. Text Domain ani FIOTRANSACTIONS_NAME prosím neměň.

**Comment by kalich5** [comment]
Napsal jsem, jestli by nešlo fio-transactions

Tam o tom, že je to banka není ani slovo. Uvidíme, co odpoví

**Comment by kalich5** [comment]
Again. YOU don't represent FIO bank.

You can't start your slug with their name, be it fio-bank or even just fio.

You can do woo-fio-bank or transactions-fio-bank but unless this is an official, owned by FIO, product, you don't get to appropriate their name.

**Comment by kalich5** [comment]
Tak co zkusit **skaut-fio-bank-transactions** - to nám navrhoval na začátku

**Comment by kalich5** [comment]
Tak bychom měli mít **skaut-fio-bank-transactions**, jen co to povolí.

Povolil tu blbou verzi z prvního emailu. Tak čekám na opravu.
Damn it.... Sorry, that's 100% my fault. When you said "This is what you wrote in the first email." I just assumed that you meant I'd gotten it right in the first email (which ... says sakut-fio-bank-transactions so obviously I didn't).

You'll have to resubmit and I'll fix that, but we can't rename a slug once approved :(

**Comment by kalich5** [comment]
Repozitář je vytvořený. Obrázky máme vytvořené. Už jen dodělat plugin.
