### ISSUE TITLE
Aktualizovat knihovni FIO API

### ISSUE THREAD

**Issue by kalich5** [skaut/skaut-fio-bank-transactions#5]
Máme 4.0.1 a nově je 4.1.0
https://github.com/mhujer/fio-api-php

**Comment by kalich5** [comment]
Dokud nepůjde na wp.org nahrávat soubory PHP 7.1, není možno dořešit.

**Comment by Kejmi** [comment]
Proto nikde nevidím shortcode pro vložení na stránky?

**Comment by kalich5** [comment]
opraveno
